"""rename department

Revision ID: 4898cbfd01b0
Revises: b766aea6b6b0
Create Date: 2024-07-01 08:08:32.193055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4898cbfd01b0'
down_revision = 'b766aea6b6b0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
